### PR TITLE
support retry-after http header #10

### PR DESCRIPTION
**Pull request by kof**
- its rfc compliant
- tests added
- jshint passes
- added umd support https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

### CODE REVIEW

**Comment by kof** [comment]
I was not able to produce dist files

Testing jquery.ajax-retry.htmlevents.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1028:32)
    at child_process.js:1109:20
    at process._tickCallback (node.js:343:11)
    at Function.Module.runMain (module.js:492:11)
    at startup (node.js:124:16)
    at node.js:807:3

Grunt stuff is very much outdated.

**Comment by johnkpaul** [comment]
Thanks, @kof! I've merged this in as well as updated grunt to 0.4. You should be able to run the normal grunt CLI now.

**Comment by kof** [comment]
thanks, please create a new git tag for this release too, so we can install it via bower

**Comment by johnkpaul** [comment]
@kof Done.

**Comment by kof** [comment]
Oh we forgot documentation :)

**Comment by kof** [comment]
grunt works now

**Comment by johnkpaul** [comment]
@kof yes, we did. Can you write something up in a new PR? Thanks.

**Pull request merged**
